# Generated by Django 4.2.1 on 2023-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "teacher"),
                    ("admin", "admin"),
                    ("student", "student"),
                ],
                max_length=128,
            ),
        ),
    ]
